- name: Create the config directory
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Write the RKE2 config
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0600"
  no_log: true
  notify: Restart rke2-agent
